/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "teleportation"
include(":bteg-teleportation-api")
include(":bteg-teleportation-bukkit")
include(":bteg-teleportation-velocity")
project(":bteg-teleportation-api").projectDir = file("API")
project(":bteg-teleportation-bukkit").projectDir = file("Bukkit")
project(":bteg-teleportation-velocity").projectDir = file("Velocity")
