name: BTEGTeleportation
version: '${project.version}'
api-version: '1.20'
main: de.btegermany.teleportation.TeleportationBukkit.TeleportationBukkit
author: JaskerX
description: This plugin covers most teleportation functions across the network.
loadbefore: [Essentials]

commands:
  tp:
    description: Teleport to another player.
    usage: /tp [player]
  tpa:
    description: Send a teleportation request to another player.
    usage: /tpa [player]
  tpaccept:
    description: Accept a teleportation request.
    usage: /tpaccept (optional [player])
  tpadeny:
    description: Deny a teleportation request.
    usage: /tpadeny (optional [player])
  tpacancel:
    description: Cancel a teleportation request.
    usage: /tpacancel
  tphere:
    description: Teleport a player to you.
    usage: /tphere [player]
  tpback:
    description: Teleport back to the location you have been teleported from.
    usage: /tpback
  warp:
    usage: |
      /nwarp
      /nwarp [search]
      /nwarp help
      /nwarp create [name; city; state; (optional: headId)]
      /nwarp change [id] [name/city/state/coordinates/headId] [value]
      /nwarp change [id] [yaw/pitch/height]
      /nwarp delete [id]
      /nwarp tag [tag] add/remove [warpId]
      /nwarp tag [tag old] edit [tag new]
    aliases:
      - nwarp
  lobbywarp:
    usage: |
      /lobbywarp [city]
      /lobbywarp add [city] [center-latitude] [center-longitude] [radius]
      /lobbywarp remove [city]