# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
[versions]
com-google-code-gson-gson = "2.14.0"
com-google-guava-guava = "33.6.0-jre"
com-mojang-authlib = "4.0.43"
com-mysql-mysql-connector-j = "9.7.0"
com-velocitypowered-velocity-api = "4.1.0-SNAPSHOT"
commons-io-commons-io = "2.22.0"
io-netty-netty-buffer = "4.2.15.Final"
io-papermc-paper-paper-api = "1.21.10-R0.1-SNAPSHOT"
junit-junit = "4.13.2"
li-cinnazeyy-langlibs-api = "1.5.2"
net-buildtheearth-terraminusminus-terraminusminus-bukkit = "2.2.0-1.21.8"
org-json-json = "20260522"
# https://plugins.gradle.org/plugin/io.freefair.lombok
lombok = "9.5.0"
# https://github.com/GradleUp/shadow/releases
shadow = "9.6.0"
# https://mvnrepository.com/artifact/com.github.spotbugs/spotbugs-annotations
spotbugs-annotations = "4.10.2"
dev-triumphteam-triumph-gui = "3.1.13"
net-wesjd-anvilgui = "1.10.13-SNAPSHOT"

[libraries]
com-google-code-gson-gson = { module = "com.google.code.gson:gson", version.ref = "com-google-code-gson-gson" }
com-google-guava-guava = { module = "com.google.guava:guava", version.ref = "com-google-guava-guava" }
com-mojang-authlib = { module = "com.mojang:authlib", version.ref = "com-mojang-authlib" }
com-mysql-mysql-connector-j = { module = "com.mysql:mysql-connector-j", version.ref = "com-mysql-mysql-connector-j" }
com-velocitypowered-velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "com-velocitypowered-velocity-api" }
commons-io-commons-io = { module = "commons-io:commons-io", version.ref = "commons-io-commons-io" }
io-netty-netty-buffer = { module = "io.netty:netty-buffer", version.ref = "io-netty-netty-buffer" }
io-papermc-paper-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "io-papermc-paper-paper-api" }
junit-junit = { module = "junit:junit", version.ref = "junit-junit" }
li-cinnazeyy-langlibs-api = { module = "li.cinnazeyy:LangLibs-API", version.ref = "li-cinnazeyy-langlibs-api" }
net-buildtheearth-terraminusminus-terraminusminus-bukkit = { module = "net.buildtheearth.terraminusminus:terraminusminus-bukkit", version.ref = "net-buildtheearth-terraminusminus-terraminusminus-bukkit" }
org-json-json = { module = "org.json:json", version.ref = "org-json-json" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }
dev-triumphteam-triumph-gui = { module = "dev.triumphteam:triumph-gui", version.ref = "dev-triumphteam-triumph-gui" }
net-wesjd-anvilgui = { module = "net.wesjd:anvilgui", version.ref = "net-wesjd-anvilgui" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
