/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
}

repositories {
    //mavenLocal() // NEVER use in production builds/push
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://libraries.minecraft.net/")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }

    maven {
        url = uri("https://mvn.alps-bte.com/repository/alps-bte/")
    }

    maven {
        url = uri("https://repo.dachstein.cloud/nexus/content/repositories/btegermany")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://maven.daporkchop.net/")
    }

    maven {
        url = uri("https://maven.smyler.net/releases/")
    }
}

group = "de.btegermany"

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
