/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    alias(libs.plugins.shadow)
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(project(":bteg-teleportation-api"))
    implementation(libs.org.json.json)
    implementation(libs.spotbugs.annotations)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.mojang.authlib)
    compileOnly(libs.li.cinnazeyy.langlibs.api)
    implementation(libs.dev.triumphteam.triumph.gui) {
        exclude (group = "org.jetbrains", module = "annotations")
        exclude (group = "net.kyori", module = "adventure-api")
        exclude (group = "net.kyori", module = "adventure-platform-bukkit")
        exclude (group = "net.kyori", module = "adventure-text-serializer-gson")
        exclude (group = "net.kyori", module = "adventure-text-serializer-legacy")
    }
    compileOnly(libs.net.wesjd.anvilgui)
}

description = "Teleportation.bukkit"

tasks.shadowJar {
    archiveClassifier = ""

    relocationPrefix = "$group.TeleportationVelocity.shaded"
    enableAutoRelocation = true
}

tasks.assemble {
    dependsOn(tasks.shadowJar) // Ensure that the shadowJar task runs before the build task
}

tasks.jar {
    archiveClassifier = "UNSHADED"
    enabled = false // Disable the default jar task since we are using shadowJar
}

// seperate block because of version serialization
if (true) {
    val globalVersion = "1.1.3"
    version = globalVersion

    val processPluginYml by tasks.registering {
        val inputFile = file("src/main/resources/plugin.yml.template")
        val outputFile = file("src/main/resources/plugin.yml")

        inputs.file(inputFile)
        outputs.file(outputFile)

        doLast {
            val content = inputFile.readText().replace("\${version}", globalVersion)
            outputFile.writeText(content)
        }
    }

    tasks.named("processResources") {
        dependsOn(processPluginYml)
    }
}