/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    alias(libs.plugins.shadow)
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(project(":bteg-teleportation-api"))
    implementation(libs.com.tchristofferson.pagedinventories)
    implementation(libs.org.json.json)
    implementation(libs.spotbugs.annotations)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.mojang.authlib)
    compileOnly(libs.li.cinnazeyy.langlibs.api)
}

description = "Teleportation.bukkit"

tasks.shadowJar {
    archiveClassifier = ""

    relocationPrefix = "$group.TeleportationVelocity.shaded"
    enableAutoRelocation = true
}

tasks.assemble {
    dependsOn(tasks.shadowJar) // Ensure that the shadowJar task runs before the build task
}

tasks.jar {
    archiveClassifier = "UNSHADED"
    enabled = false // Disable the default jar task since we are using shadowJar
}
