/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.google.guava.guava)
}

description = "Teleportation.api"
