/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    alias(libs.plugins.shadow)
    alias(libs.plugins.lombok)
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(project(":bteg-teleportation-api"))
    implementation(libs.net.buildtheearth.terraminusminus.terraminusminus.bukkit)
    implementation(libs.com.google.guava.guava)
    implementation(libs.org.json.json)
    implementation(libs.com.mysql.mysql.connector.j)
    implementation(libs.commons.io.commons.io)
    implementation(libs.io.netty.netty.buffer)
    implementation(libs.com.google.code.gson.gson)
    testImplementation(libs.junit.junit)
    compileOnly(libs.com.velocitypowered.velocity.api)
    annotationProcessor(libs.com.velocitypowered.velocity.api)
}

description = "Teleportation.velocity"

tasks.shadowJar {
    archiveClassifier = ""

    relocationPrefix = "$group.TeleportationVelocity.shaded"
    enableAutoRelocation = true
}

tasks.assemble {
    dependsOn(tasks.shadowJar) // Ensure that the shadowJar task runs before the build task
}

tasks.jar {
    archiveClassifier = "UNSHADED"
    enabled = false // Disable the default jar task since we are using shadowJar
}

// seperate block because of version serialization
if (true) {
    val globalVersion = "2.0.0"
    version = globalVersion

    val processPluginYml by tasks.registering {
        val inputFile = file("src/main/resources/velocity-plugin.json.template")
        val outputFile = file("src/main/resources/velocity-plugin.json")

        inputs.file(inputFile)
        outputs.file(outputFile)

        doLast {
            val content = inputFile.readText().replace("\${version}", globalVersion)
            outputFile.writeText(content)
        }
    }

    tasks.named("processResources") {
        dependsOn(processPluginYml)
    }
}